- name: demo on variable on play
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print variable
      debug:
        msg: URL = {{URL}}
    - name: print variable from task declearation
      vars:
        URL: task.google.com
      debug:
        msg: URL = {{URL}}
- name: declear the variables in a file and access them
  hosts: all
  vars_files:
    - sample.yaml
  tasks:
    - name: print variable
      debug:
        msg: URL = {{URL}}
- name: Decleare variable from inventory
  hosts: all
  tasks:
    - name: print variable
      debug:
        msg: URL = {{URL}}
- name: variable precedence
  hosts:
  vars:
    URL: play.example.com
  vars_files:
    - sample.yaml
  tasks:
    - name: print variable
      debug:
        msg: URL = {{URL}}
      vars:
        URL: URL = {{URL}}


