- name: demo on variable on play
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print variable
      debug:
        msg: URL = {{URL}}
    - name: print variable from task declearation
      vars:
        URL: task.google.com
      debug:
        msg: URL = {{URL}}
- name: declear the variables in a file and access them
  hosts: all
  vars_files:
    - sample.yaml
  tasks:
    - name: print variable
      debug:
        msg: URL = {{URL}}
- name: Decleare variable from inventory
  hosts: all
  tasks:
    - name: print variable
      debug:
        msg: URL = {{URL}}
- name: variable precedence
  hosts: all
  vars:
    URL: play.example.com
  vars_files:
    - sample.yaml
  tasks:
    - name: print variable
      debug:
        msg: URL = {{URL}}
      vars:
        URL: task.example.com
- name: Register a variable
  hosts: all
  tasks:
    - name: Find files
      find:
        paths: /boot
      register: OUTPUT
    - name: Print Output
      debug:
        msg: OUTPUT = {{OUTPUT}}
- name: Take input from user
  hosts: all
  vars_input:
    - name: URL
      prompt: Enter URL
      private: no
    tasks:
      - name: Print variable
        debug:
          msg: URL = {{URL}}


