- name: demo on variable on play
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print variable
      debug:
        msg: URL = {{URL}}
    - name: print variable from task declearation
      vars:
        URL: task.google.com
      debug:
        msg: URL = {{URL}}
